server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka/

spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
         include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

